server:
  port: 8083
  servlet:
    context-path: /api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_db
    username: root
    password: 111111
ljh:
  client:
    access-key: dada
    secret-key: kjkll
