spring:
  application:
    name: ljh-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_db
    username: root
    password: 111111
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



  # session 失效时间（分钟）
  session:
    timeout: 86400

  # redis 配置
  redis:
    port: 6379
    host: 192.168.123.4
    database: 1
    password: 12052497
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)



ljh:
  client:
    secret-key: qweqw
    access-key: qweqw

dubbo:
  application:
    name: dubbo-springboot-ljh-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段